version: 2

build:
  image: stable
  python: "3.10"

conda:
  environment: environment.yml

python:
  system_packages: true
  install:
    - method: pip
      path: .
      extra_requirements:
         - doc
         - plotting
         - bloch_sphere_visualization
         - fancy_progressbar
