version: 2

build:
  image: stable

conda:
  environment: environment.yml
  
python:
  system_packages: true
  install:
    - method: pip
      path: .
      extra_requirements:
         - doc
         - fancy_progressbar
