version: 2

conda:
  file: environment.yml

sphinx:
  configuration: doc/source/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
         - doc
         - fancy_progressbar
