version: 2

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-latest

conda:
  environment: environment.yml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
         - doc
         - plotting
         - bloch_sphere_visualization

sphinx:
  builder: html
  configuration: doc/source/conf.py

formats:
  - pdf
  - epub
